### ISSUE TITLE
evernode: command not found

### ISSUE THREAD

**Issue by jebatradz** [HotPocketDev/evernode-host#47]
I wasn't able to use the evernode command, I can't provide the log file since the evernode command is not working for me.
sashimono directory and its content exist but the evernode command is just not there. Should I reinstall and use another host?

**Comment by chalith** [comment]
@jebatradz Any update on the issue? Did you terminate the server?

**Comment by jebatradz** [comment]
Thanks for the email.I had to terminate the server and start a new one since the command was not available and I couldn't install the server since it's already installed but the command wasn't reacheable. I've reinstalled and the host is working fine and currently on Active mode

**Comment by chalith** [comment]
Cool, Good to hear @jebatradz. I will close the issue.
