### ISSUE TITLE
TCP connections log on `evernode log`

### ISSUE THREAD

**Issue by wojake** [HotPocketDev/evernode-host#54]
A new log section on `evernode log` which contains all the incoming TCP connections initialized by users & tenants.

Rationale:
https://github.com/HotPocketDev/evernode-host/discussions/53

**Comment by ravinsp** [comment]
I think this would be an overkill to provide this inside sashimono/evernode tooling. There are standard network monitoring/logging tools available for Linux which would be better than anything we would come up with.
Our time is better spent by doing evernode specific stuff and the rest can be extended/enhanced by people with better linux administrative tooling experience.

**Comment by wojake** [comment]
Agreed, thank you!
