### ISSUE TITLE
Clarification needed in the README around what ports are expected to be used.

### ISSUE THREAD

**Issue by rippleitinnz** [HotPocketDev/evernode-host#57]
![image](https://user-images.githubusercontent.com/42262747/183560882-39ac5be6-3eb8-45b0-9ab0-93a1f38625ed.png)

**Comment by kithminisg** [comment]
@rippleitinnz , Thank you for informing us of the issue in the README. We have updated the [Firewalls and Ports](https://github.com/HotPocketDev/evernode-host#important-tips) section accordingly.
