### ISSUE TITLE
Deployed contracts not matching set instance sizes

### ISSUE THREAD

**Issue by xVet** [HotPocketDev/evernode-host#59]
Hi there,

i have noticed the following with 2 nodes:

The deployed contracts on the nodes do not fit to the instance size set by the operator.

Node 1:
This node has 1 lease.
You can see that per instance there's a maximum of 1% cpu reserved for this ( see in image "Node 1"). A contract that is leasing 1 instance should therefore not exceed these limits.

![Node 1](https://user-images.githubusercontent.com/109047316/184426693-9ad4e03e-c85e-4e41-8958-c081625ef27e.png)

By monitoring this exact node I observed that the instance is using 5% cpu on average constantly ( see in image "Node 1 cpu").
But it should be roughly 1% cpu usage!

![Node 1 cpu](https://user-images.githubusercontent.com/109047316/184426727-7a17317b-6383-46d8-aa40-098c07111cd7.png)

Node 2:
This node has 2 leases.
The cpu resource reserved for 1 instance is here 6.67% (see image "Node 2") . 

![Node 2](https://user-images.githubusercontent.com/109047316/184426771-6f8a4b29-ac71-4e1d-85c7-11e775a668a2.png)

On this node tho the 2 leases take up around 10% in cpu power on average constantly (see image "Node 2 cpu"). It supposed be roughly 14%.

![Node 2 cpu](https://user-images.githubusercontent.com/109047316/184426790-cb8dc549-ed35-495c-8d92-bd92d9a0805b.png)

-------------------

It seems that the deployed contracts always take up 5% cpu power regardless of what the host determines to be used per instance. This scales also linearly as you can see. 1 instance lease = 5 % cpu and 2 instance leases = 10% and so on. 

This would also result in a maximum cap of leases per Host, which is 20 leases ( 20 * 5% cpu power => 100% cpu load) before performance is throttled.
!

Disclaimer:
All nodes are freshly setup exactly for testing purposes and do not run anything else besides the Evernote host. The nodes also run stock packages, no additional bloat whatsoever.

**Comment by effofexx** [comment]
Good observation, Vet! This is not something many of us would have likely noticed, given our host resources compared to yours (I've only allocated 6 instances with my current VPS, so my 13.33% CPU allocation envelopes the 5% you've observed).

Which software are you using to monitor your node and produce those plots above? I'm curious to find out what method it is using to measure CPU load because I just checked the load on my host and found that the one contract instance currently running is utilizing ~0.5% of the CPU. This is the load I see when running the `top` command, as well as on my Monitorix dashboard.

**Comment by xVet** [comment]
Good point! I use the tools of Hetzner(vps provider) to monitor it from my user dashboard (webpage).

Correct there seems to be a divergence too, via TOP ,i have on the 2 instance leased node a load of around 0.3-0.6%! The 1 instance node hovers at 0.2%.

Therefore i m not sure on the load tbh. If we go with 1 instance is around 0.1-0.5% then this could be a lower boundary on how thin you can slice your node instances. 

Granted, those are test contracts they deploy so it's okay if they use less than the set instance size. Which seems to be the case with the top command...(which i would pick to determine the true load).

**Comment by ravinsp** [comment]
@xVet Can you verify whether Hetzener CPU graph shows a deviation when running another Linux program. For example run some CPU benchmark tool and see how the top command vs Hetzener chart differs.

A Google search also revealed Hetzener chart has had similar deviation in the past for some people.

**Comment by effofexx** [comment]
FWIW I can throw in another point of reference for a VPS provider showing a discrepancy here. I use Linode and the dashboard on their website indicates that I'm using ~6.5% to 7% of my CPU while running one contract instance. Linode dashboard screenshot:

![Screenshot_20220812-204724](https://user-images.githubusercontent.com/89996356/184465800-34adde9e-739e-4f60-affb-4219867051ea.png)

Meanwhile at the exact same time, Montorix and `top` indicate that I'm using 2.3% of the CPU. Even the reported Max CPU loads over the same 24hr period do not align. One image for each core from Monitorix:

![Screenshot_20220812-204817~3](https://user-images.githubusercontent.com/89996356/184465854-e6f03bf6-9df5-4130-a53d-b1b025eb55d9.png)

![Screenshot_20220812-204836~2](https://user-images.githubusercontent.com/89996356/184465859-f60f4d62-7009-4c69-82b8-990596aa9ff2.png)

It seems both Linode and Hetzner both deviate in the same way, and almost to the same degree. I'm not sure why and whether or not the deviation is present while running other software, but I'll try to run some tests when I have more free time. I agree with @xVet that I trust `top` more than the provider, but it's interesting to see the same variation.

**Comment by xVet** [comment]
@ravinsp Yes I can also confirm, it's the fault of the Hetzner monitoring tool. I have Debian 11 machine in their Datacenter that's running something else and the same discrepancy can be observed!

@effofexx thanks for checking on your end as well, very interesting to see this!

Can be closed for me, thanks for your input guys!

**Comment by wojake** [comment]
Adding on: any instance/contract wouldn't be able to use more than its instance's resource (RAM/Disk space/CPU) since sashimono has put resource constraints on the instance during its initialization.

https://docs.docker.com/config/containers/resource_constraints/

**Comment by ravinsp** [comment]
@wojake yes we do enforce resource constraints but not via docker. We make use of Linux cgroups and disk quota features for this. This way, the resource constraints apply to everything related to the contract instance even outside of docker.
