### ISSUE TITLE
Sashimono issue - performing things twice

### ISSUE THREAD

**Issue by wojake** [HotPocketDev/evernode-host#60]
Host: https://dashboard.evernode.org/#/host/rsZQgYgih1KUsTGvUGGdqhsieEuJVMW73X
Host XRPL account: https://beta.bithomp.com/explorer/rsZQgYgih1KUsTGvUGGdqhsieEuJVMW73X

The host is operational and working just fine as of writing this, but there was a problem with its sashimono's instance termination process which has led it to:
- Create 2 Lease NFT
- Decrement instance count by 2
- Issue 2 NFTSellOffer tx with the same NFT

with only 1 lease NFT being burnt and 1 instance being terminated, it's only supposed to do the process above once.

##

An instance reached its expiry date and sashimono terminated the instance and burnt the tenant's lease NFT, as it should ([tx here](https://beta.bithomp.com/explorer/FC7BDB04EE947856257C8480B7887D1BDB7BC7DC6AA3DD0EDD9526CA3ABDDC1A))

But the problem is, during sashimono's lease NFT burning process, it burnt it twice:
1. The first burn was successful since the ledger object (NFT) existed ([tx here](https://beta.bithomp.com/explorer/FC7BDB04EE947856257C8480B7887D1BDB7BC7DC6AA3DD0EDD9526CA3ABDDC1A))
2. But the second burn was a failure since the ledger object (NFT) has been burnt in the past ([tx here](https://beta.bithomp.com/explorer/315D75B99E968A50835E166CDD8CFD3E3C58722A9EB7B0CC552AB762E8363B9D))

It then proceeded to mint 2 instance NFT (NFT-ID's last 2 digits: 86 & 87) but only put up lease NFT #87 up for sale on the DEX:
1. 1st NFTSellOffer ([tx here](https://beta.bithomp.com/explorer/D301963CEC877B580A9D853504F2A34046670DF4EA3FA0126C65F7166531DB86))
2. 2nd NFTSellOffer ([tx here](https://beta.bithomp.com/explorer/95BA1AF47D1A7A919BE0B963F0BE500D6ACF990F49F450FDF02FA33DBC155E05))

Look at the NFT being sold, it's the same NFT ID: 000100001C1154B8B9338FBE530B9B3BB2A8B795C4DCEEA413314122000000***87***

After the process is over, sashimono then sent a Instance Count decrement request to the Hook to reduce its instance count (-1) but it sent it twice, resulting in the instance count being -1 or 4294967267

# Note for host operators
If you run a host with the XRPL address **`rsZQgYgih1KUsTGvUGGdqhsieEuJVMW73X`**, please provide the log file to the team.

**Comment by chalith** [comment]
We've found the cause for this bug and we are fixing the issue. The fix will be resolved and released soon.
