### ISSUE TITLE
Node version issue.

### ISSUE THREAD

**Issue by lathanbritz** [HotPocketDev/evernode-host#62]
figured out my iprouting issues so trying to set this up on another server here at home now, came across this issue iv got node 17+ and its failing.

<img width="908" alt="Screen Shot 2022-08-30 at 19 38 34" src="https://user-images.githubusercontent.com/508629/187562147-b0735d13-ff9d-49e2-960a-c814ca60071c.png">

**Comment by chalith** [comment]
Thank you @lathanbritz, We'll fix this issue and release soon

**Comment by chalith** [comment]
@lathanbritz we've resolved this issue and released a minor version. You can try now.

**Comment by lathanbritz** [comment]
beautiful, works like a charm new host up .
