### ISSUE TITLE
Installation Failed on Oracle Cloud Linux VM

### ISSUE THREAD

**Issue by rohithc9595** [HotPocketDev/evernode-host#63]
[installer-1665140005.log](https://github.com/HotPocketDev/evernode-host/files/9733879/installer-1665140005.log)

Attaching log file

**Comment by chalith** [comment]
@rohithc9595 Thank you, We'll look into the issue and keep you updated.

**Comment by Udith-Gayan** [comment]
Hi @rohithc9595 , We couldn't find an exact reason  for the issue you mentioned. Nevertheless, to have clue about the issue, would you be able to follow the instructions below and send us the output ?

1. Unzip the following zipped folder: [dist.zip](https://github.com/HotPocketDev/evernode-host/files/9762852/dist.zip)
2. Open the terminal inside the unzipped  'dist' folder.
3. Run `node index.js`

Please send us the output on the terminal.

**Comment by rohithc9595** [comment]
@Udith-Gayan Followed above steps. Attaching the terminal output.
[Terminal output on running command node indexdotjs.txt](https://github.com/HotPocketDev/evernode-host/files/9764513/Terminal.output.on.running.command.node.indexdotjs.txt)

**Comment by Udith-Gayan** [comment]
@rohithc9595  Could you check if there are any pending OS/kernel updates ? If there are any, please update the kernel  and retry to install sashimono. Please let us know the results.

**Comment by rohithc9595** [comment]
@Udith-Gayan No change in results after update. Issue still persists.

**Comment by ravinsp** [comment]
This is weird. Can you send the output of the following two commands: `lsb_release -a` and `arch` ?
Also, can you post a screenshot/link to the VM size/tier you used in Oracle Cloud? Thank you.

**Comment by rohithc9595** [comment]
@ravinsp 
1] 
ubuntu@myubuntu:~$ arch
aarch64

2]
ubuntu@myubuntu:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.5 LTS
Release:	20.04
Codename:	focal

3]
Oracle Free Cloud Tier, 
VM.Standard.A1.Flex, Ampere ARM based processor

**Comment by ravinsp** [comment]
@rohithc9595 oh this explains everything. Evernode software is not compiled for ARM CPU architecture. I will only run on x86_64. Looks like we have to make this clear in the installation docs.
