### ISSUE TITLE
grub issues

### ISSUE THREAD

**Issue by gadget78** [HotPocketDev/evernode-host#64]
have installed this within a docker environment, playing around... 
but can only get up to the "grub" installation part, as it doesn't have bootloader systems ... 

any way around this issue ? to be able to support dockers and not restricted to just VM ? 
as i got this far, or would a docker in docker be the next breaking point anyhows ? .. 
betas are all about testing things ! 

[installer-1665526196.log](https://github.com/HotPocketDev/evernode-host/files/9760190/installer-1665526196.log)

**Comment by ravinsp** [comment]
@gadget78 At this time, we have no plans to support this in containerized environments. In addition to getting distracted from our primary goals, there are technical limitations that prevents this from happening as well. Maybe in the future...
