### ISSUE TITLE
Outdated hosts aren't able to submit their heartbeat tx

### ISSUE THREAD

**Issue by wojake** [HotPocketDev/evernode-host#65]
Due to the new update being implemented on the registry hook, outdated hosts (version 0.5.12 and below) aren't able to submit their Heartbeat transaction to the Hook.

All Evernode Hosts that are outdated risk of getting kicked out of the registry hook if they fail to update within 2 weeks' time. Please update your host.

**Comment by kithminisg** [comment]
@wojake, In Sashimono there is a built-in auto-update feature to fetch the latest updates.

Hopefully, the hosts will be updated to the latest version within a day.

**Comment by wojake** [comment]
Completely forgotten about that feature haha, thanks.
